### ISSUE TITLE
Add usage example to README

### ISSUE THREAD

**Issue by gfogle** [ryanmcdermott/react-native-login#2]
Unless I'm missing something, would be nice to have an example of usage within a react native app

**Comment by ryanmcdermott** [comment]
Thanks for opening an issue! This could be expanded to be included inside a larger example project, perhaps one that was using some Flux implementation. As it is, this project itself is sort of a self-contained example, but maybe it's not the best it could be! Right now, my big concern is getting it upgraded to the latest version of RN (that being 0.17) Would love help on either front.
