### ISSUE TITLE
iOS build failure

### ISSUE THREAD

**Issue by sharq1** [ryanmcdermott/react-native-login#4]
Followed the instructions, installed everything from React Native Getting Started page as well, but the build fails due to dependencies inside `react-native-cookies` folder. When I install the dependencies there another unmet dependencies appear deeper.

Why Is `react-native-cookies` folder there in the first place instead of depending on `npm`?

![image](https://cloud.githubusercontent.com/assets/1241239/14635100/3f0ce444-0625-11e6-8967-43d0b086b77b.png)

**Comment by annahowell** [comment]
You can fix this by going in to the folders and npm installing each one by hand, it's hacky but it works if you're stuck

**Comment by annahowell** [comment]
[node_modules.zip](https://github.com/ryanmcdermott/react-native-login/files/226074/node_modules.zip)
Or put this in:

react-native-login/ReactNativeLogin/iOS/react-native-cookies

**Comment by ryanmcdermott** [comment]
Sorry about that! I tried to keep `react-native-cookies` as a reference. @annabel82 You're fix would work as well. Anyone eager to open a PR? I can't get to it at the moment but this seems like it's pretty straightforward, I hope!

**Comment by annahowell** [comment]
i don't know enough about it all sorry, i've been using react native and npm for < 48 hours

**Comment by ryanmcdermott** [comment]
@annabel82 No worries at all. Enjoy learning them! If @sharq1 gets a fix I would love to incorporate it! Otherwise, I can look at this hopefully soon.

**Comment by sharq1** [comment]
Sorry, I won't be able to provide a fix, as I've decided not to use react-native-login in favor of starter kit with auth already implemented.

**Comment by ryanmcdermott** [comment]
Understandable. Best of luck.

When I get some time to get around to this issue, I will resolve it. Otherwise if anyone else has a quick fix I would much appreciate it!

**Comment by annahowell** [comment]
sharq1 may i ask for a link to the starter kit please?

**Comment by sharq1** [comment]
@annabel82 https://github.com/bartonhammond/snowflake

**Comment by annahowell** [comment]
Thanks sharq1 :)

**Comment by hbd** [comment]
iOS build worked for me with node:
`nvm version` : `v5.4.1`

and did not work with node version `0.12.7`

**Comment by rocwong-cn** [comment]
@sharq1 Thx for your link !!!!
