### ISSUE TITLE
Cookie null

### ISSUE THREAD

**Issue by valinaga** [ryanmcdermott/react-native-login#8]
Hi,

I buid the example but always get cookie null, even if it was set in the browser by the server.
Any idea?
Thanks,

**Comment by ryanmcdermott** [comment]
I need to run this again, it's been a little while. I don't think it was something related to dependency changes. I will look.

**Comment by homeslicesolutions-zz** [comment]
I am also seeing this issue.  Is there a problem with "https" and grabbing those cookies?

**Comment by homeslicesolutions-zz** [comment]
I have made PR #10 for this fix

**Comment by ryanmcdermott** [comment]
Should be fixed in #10
