### ISSUE TITLE
How to connect to backend?

### ISSUE THREAD

**Issue by MakarkinPRO** [ryanmcdermott/react-native-login#9]
Hi, is it possible to connect with my backend? 

Do you have contacts may be Email, skype. Thx.

**Comment by ryanmcdermott** [comment]
Hey there! Yes it's certainly possible to connect to the backend. Just change this line to your server's URL! https://github.com/ryanmcdermott/react-native-login/blob/master/ReactNativeLogin/App/components/App.js#L8

I hope this helps :)
